<x-menu>
    <livewire:mi-agenda 
        :paciente="$paciente"
        :citas="$citas"
        :total="$total"
        :programadas="$programadas"
        :asistidas="$asistidas"
        :canceladas="$canceladas"
        :meses="$meses"
        :conteos="$conteos"
        :proxCita="$proxCita"
        :tiempoRestante="$tiempoRestante"
    />
</x-menu>
